In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('C:/Users/wesle/Desktop/Graduação Eng Química/DataSciencePython/DataScienceDSA/datasets_4511_6897_diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.shape
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [34]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [33]:
colunas_x = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
nozero = df.replace(0, df[colunas_x].mean())
nozero
#Trocando os zeros pela média dos valores

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.0,72.000000,35.000000,79.799479,33.600000,0.627,50,1
1,1.000000,85.0,66.000000,29.000000,79.799479,26.600000,0.351,31,0
2,8.000000,183.0,64.000000,20.536458,79.799479,23.300000,0.672,32,1
3,1.000000,89.0,66.000000,23.000000,94.000000,28.100000,0.167,21,0
4,3.845052,137.0,40.000000,35.000000,168.000000,43.100000,2.288,33,1
5,5.000000,116.0,74.000000,20.536458,79.799479,25.600000,0.201,30,0
6,3.000000,78.0,50.000000,32.000000,88.000000,31.000000,0.248,26,1
7,10.000000,115.0,69.105469,20.536458,79.799479,35.300000,0.134,29,0
8,2.000000,197.0,70.000000,45.000000,543.000000,30.500000,0.158,53,1
9,8.000000,125.0,96.000000,20.536458,79.799479,31.992578,0.232,54,1
10,4.000000,110.0,92.000000,20.536458,79.799479,37.600000,0.191,30,0
11,10.000000,168.0,74.000000,20.536458,79.799479,38.000000,0.537,34,1
12,10.000000,139.0,80.000000,20.536458,79.799479,27.100000,1.441,57,0
13,1.000000,189.0,60.000000,23.000000,846.000000,30.100000,0.398,59,1
14,5.000000,166.0,72.000000,19.000000,175.000000,25.800000,0.587,51,1
15,7.000000,100.0,69.105469,20.536458,79.799479,30.000000,0.484,32,1
16,3.845052,118.0,84.000000,47.000000,230.000000,45.800000,0.551,31,1
17,7.000000,107.0,74.000000,20.536458,79.799479,29.600000,0.254,31,1
18,1.000000,103.0,30.000000,38.000000,83.000000,43.300000,0.183,33,0
19,1.000000,115.0,70.000000,30.000000,96.000000,34.600000,0.529,32,1
20,3.000000,126.0,88.000000,41.000000,235.000000,39.300000,0.704,27,0
21,8.000000,99.0,84.000000,20.536458,79.799479,35.400000,0.388,50,0
22,7.000000,196.0,90.000000,20.536458,79.799479,39.800000,0.451,41,1
23,9.000000,119.0,80.000000,35.000000,79.799479,29.000000,0.263,29,1
24,11.000000,143.0,94.000000,33.000000,146.000000,36.600000,0.254,51,1
25,10.000000,125.0,70.000000,26.000000,115.000000,31.100000,0.205,41,1
26,7.000000,147.0,76.000000,20.536458,79.799479,39.400000,0.257,43,1
27,1.000000,97.0,66.000000,15.000000,140.000000,23.200000,0.487,22,0
28,13.000000,145.0,82.000000,19.000000,110.000000,22.200000,0.245,57,0
29,5.000000,117.0,92.000000,20.536458,79.799479,34.100000,0.337,38,0
...,...,...,...,...,...,...,...,...,...
738,2.000000,99.0,60.000000,17.000000,160.000000,36.600000,0.453,21,0
739,1.000000,102.0,74.000000,20.536458,79.799479,39.500000,0.293,42,1
740,11.000000,120.0,80.000000,37.000000,150.000000,42.300000,0.785,48,1
741,3.000000,102.0,44.000000,20.000000,94.000000,30.800000,0.400,26,0
742,1.000000,109.0,58.000000,18.000000,116.000000,28.500000,0.219,22,0
743,9.000000,140.0,94.000000,20.536458,79.799479,32.700000,0.734,45,1
744,13.000000,153.0,88.000000,37.000000,140.000000,40.600000,1.174,39,0
745,12.000000,100.0,84.000000,33.000000,105.000000,30.000000,0.488,46,0
746,1.000000,147.0,94.000000,41.000000,79.799479,49.300000,0.358,27,1
747,1.000000,81.0,74.000000,41.000000,57.000000,46.300000,1.096,32,0
748,3.000000,187.0,70.000000,22.000000,200.000000,36.400000,0.408,36,1
749,6.000000,162.0,62.000000,20.536458,79.799479,24.300000,0.178,50,1
750,4.000000,136.0,70.000000,20.536458,79.799479,31.200000,1.182,22,1
751,1.000000,121.0,78.000000,39.000000,74.000000,39.000000,0.261,28,0
752,3.000000,108.0,62.000000,24.000000,79.799479,26.000000,0.223,25,0
753,3.845052,181.0,88.000000,44.000000,510.000000,43.300000,0.222,26,1
754,8.000000,154.0,78.000000,32.000000,79.799479,32.400000,0.443,45,1
755,1.000000,128.0,88.000000,39.000000,110.000000,36.500000,1.057,37,1
756,7.000000,137.0,90.000000,41.000000,79.799479,32.000000,0.391,39,0
757,3.845052,123.0,72.000000,20.536458,79.799479,36.300000,0.258,52,1
758,1.000000,106.0,76.000000,20.536458,79.799479,37.500000,0.197,26,0
759,6.000000,190.0,92.000000,20.536458,79.799479,35.500000,0.278,66,1
760,2.000000,88.0,58.000000,26.000000,16.000000,28.400000,0.766,22,0
761,9.000000,170.0,74.000000,31.000000,79.799479,44.000000,0.403,43,1
762,9.000000,89.0,62.000000,20.536458,79.799479,22.500000,0.142,33,0
763,10.000000,101.0,76.000000,48.000000,180.000000,32.900000,0.171,63,0
764,2.000000,122.0,70.000000,27.000000,79.799479,36.800000,0.340,27,0
765,5.000000,121.0,72.000000,23.000000,112.000000,26.200000,0.245,30,0
766,1.000000,126.0,60.000000,20.536458,79.799479,30.100000,0.349,47,1
767,1.000000,93.0,70.000000,31.000000,79.799479,30.400000,0.315,23,0

In [35]:
num_True = df.loc[df['Outcome'] == 1]
num_False = df.loc[df['Outcome'] == 0]
#print(f'O número de diabéticos são: {len(num_True)})
#print(f'O número de não diabíticos são: {len(num_False)})
print(len(num_True))
print(len(num_False))
y = df['Outcome']
x = nozero.drop('Outcome', axis=1)

268
500

In [36]:
y.head(10)

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
8    1
9    1
Name: Outcome, dtype: int64

In [37]:
x.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.000000,148.0,72.000000,35.000000,79.799479,33.600000,0.627,50
1,1.000000,85.0,66.000000,29.000000,79.799479,26.600000,0.351,31
2,8.000000,183.0,64.000000,20.536458,79.799479,23.300000,0.672,32
3,1.000000,89.0,66.000000,23.000000,94.000000,28.100000,0.167,21
4,3.845052,137.0,40.000000,35.000000,168.000000,43.100000,2.288,33
5,5.000000,116.0,74.000000,20.536458,79.799479,25.600000,0.201,30
6,3.000000,78.0,50.000000,32.000000,88.000000,31.000000,0.248,26
7,10.000000,115.0,69.105469,20.536458,79.799479,35.300000,0.134,29
8,2.000000,197.0,70.000000,45.000000,543.000000,30.500000,0.158,53
9,8.000000,125.0,96.000000,20.536458,79.799479,31.992578,0.232,54

In [39]:
#Dividindo os dados de forma randômica
from sklearn.model_selection import train_test_split
x_teste,x_treino,y_teste,y_treino = train_test_split(x,y,test_size=0.3, random_state=42)

In [40]:
len(x_teste)

537

In [41]:
#Importando o modelo
from sklearn.naive_bayes import GaussianNB

In [43]:
modelo = GaussianNB()
modelo

GaussianNB(priors=None, var_smoothing=1e-09)

In [44]:
modelo.fit(x_treino,y_treino)

GaussianNB(priors=None, var_smoothing=1e-09)

In [45]:
# Testar a acurácia do método com os dados de treino, mas é melhor usar os dados de treino
from sklearn import metrics

In [47]:
previsoes_treino = modelo.predict(x_treino)
previsoes_treino

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [54]:
acuracia = metrics.accuracy_score(y_treino,previsoes_treino)
acuracia*100

74.45887445887446

In [55]:
previsoes_teste = modelo.predict(x_teste)
acuracia_treino = metrics.accuracy_score(y_teste,previsoes_teste)
acuracia_treino*100

75.23277467411546

## Alterando o algorítimo de machoneLearn para otimizar o método

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [74]:
modelo_forest = RandomForestClassifier()
modelo_forest.fit(x_treino,y_treino)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [75]:
prev = modelo_forest.predict(x_teste)
acu = metrics.accuracy_score(y_teste,prev)
acu*100

73.3705772811918

## Usando regressão logistíca

In [78]:
from sklearn.linear_model import LogisticRegression

In [82]:
modelo_regr = LogisticRegression()
modelo_regr.fit(x_treino,y_treino)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [84]:
acuracia_regr = metrics.accuracy_score(y_teste,modelo_regr.predict(x_teste))
acuracia_regr*100

73.9292364990689